spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toucheese_db
    username: seonik
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show-sql: true
      format_sql: true # 보기좋게 줄바꿈
      highlight_sql: true # 하이라이트
      use_sql_comments: true # 보다 쉬운 디버깅을 위해 SQL 내부에 /**/ 주석 추가
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always




