spring:
  main:
    # 처음에 나오는 Spring Logo 제거
    banner-mode: off
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    # url: jdbc:postgresql://localhost:5432/toucheese_db
    # username: seonik
    # password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true # 보기좋게 줄바꿈
      highlight_sql: true
      use_sql_comments: true
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always



