# 특별한 인자 없이 프로젝트 실행 시
# application-dev.yaml 을 사용해서 프로젝트 실행
spring:
  web:
    resources:
      add-mappings: false
  profiles:
    default: prod
  # 처음에 나오는 Spring Logo 제거
  main:
    banner-mode: off

#fcm:
#  file_path: /Users/seonik/개발/LikeLion/멋사 로켓단 2기/Toucheese-BE/src/main/resources/firebase/toucheese-fcm.json
#  url: https://fcm.googleapis.com/v1/projects/toucheese-2/messages:send
#  google_api: https://www.googleapis.com/auth/cloud-platform
#  project_id: toucheese-2

springdoc:
  packages-to-scan: com.example.toucheese_be
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API docs
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json;charset=UTF-8

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        stat: debug
        type:
          descriptor:
            sql: trace
      springframework:
        security: debug
      springdoc: warn