jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
  secret: testSecretKey20240316testSecretKey20240316testSecretKey20240316
  token:
    access-expiration-time: 3600000
    refresh-expiration-time: 86400000


spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://db-toucheese-2.cja2kuiisy1n.ap-northeast-2.rds.amazonaws.com/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-name: naver
#            client-id: ${NAVER_CLIENT_ID}
#            client-secret: ${NAVER_CLIENT_SECRET}
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope:
#              - name
#              - email
#          google:
#            client-name: google
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope:
#              - profile
#              - email
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: toucheesebe@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        stat: debug
        type:
          descriptor:
            sql: trace