name: Docker Image Delivery

on:
  workflow_dispatch:

jobs:
  deliever:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # 이미지 태그 설정
      - name: Set Image Tag
        id: image-tag
        run: echo "TAG=$(date +%s)-ci" >> "$GITHUB_OUTPUT"

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Build 진행
      - name: Build and Push the Docker image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --tag "toucheeseteam2/toucheese:$TAG" --push .

      
